# Generated by Django 5.0.6 on 2024-06-12 17:04

import slugger.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', slugger.fields.AutoSlugField(max_length=200, populate_from='name', unique=True)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='images/')),
                ('release_date', models.DateField()),
                ('lte_exists', models.BooleanField()),
            ],
        ),
    ]
